
--INSERT INTO users (id, email, password, first_name, last_name) VALUES (
--    1,
--    'testuser@gmail.com',
--    'password',
--    'Test',
--    'User'
--);

--Omitted autogenerated column to avoid exception


INSERT INTO users (email, password, first_name, last_name, bio) VALUES (
    'testuser@gmail.com',
    'password',
    'Test',
    'User',
    'This is a test account'
);


INSERT INTO users (email, password, first_name, last_name, bio) VALUES (
 
    'wpruett@test.com',
    '12345',
    'Wes',
    'Pruett',
    'My name is Wes! Thanks for visiting my profile'
);

INSERT INTO users (email, password, first_name, last_name, bio) VALUES (
    'mrTest@test.com',
    '12345',
    'Mister',
    'Test',
    'I am a test user! Thanks for visiting my profile'
);

INSERT INTO posts (text, image_url, author_id) VALUES (
    'The classic',
    'https://i.imgur.com/fhgzVEt.jpeg',
    1
),
(
    'Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat.',
    '',
    1
); 
INSERT INTO posts (text, image_url, author_id) VALUES (
	'Test 1','',2),('Test 2','',2);
	
INSERT INTO posts (text, image_url, author_id) VALUES (
'Test 1','',3),('Test 2','',3);